# Generated by Django 5.1.1 on 2024-11-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
